/**
 * Node Type Registry
 * Section 7.6 - Node Catalog và Node Definition
 * Central registry của tất cả node types và descriptors
 */

import type { NodeTypeDescriptor, NodeKind } from '../types/workflow';

export const NODE_TYPE_REGISTRY: Record<string, NodeTypeDescriptor> = {
  START: {
    typeKey: 'START',
    kind: 'BOUNDARY',
    displayName: 'Start',
    icon: 'PlayCircle',
    color: '#8B5CF6',
    configSchema: { type: 'object', properties: { name: { type: 'string' } }, required: ['name'] },
    inputPorts: [],
    outputPorts: [{ id: 'out', portKey: 'STARTED', semantic: 'SUCCESS', label: 'Started' }],
    supportedScopes: ['INSTANCE'],
    supportsSla: false,
    supportsForm: false,
    supportsAssignee: false,
    handlerKey: 'start',
  },
  END: {
    typeKey: 'END',
    kind: 'TERMINAL',
    displayName: 'End',
    icon: 'StopCircle',
    color: '#EF4444',
    configSchema: {
      type: 'object',
      properties: {
        endType: { type: 'string', enum: ['SUCCESS', 'REJECTED', 'CANCELLED', 'CUSTOM'] },
        name: { type: 'string' },
      },
      required: ['endType'],
    },
    inputPorts: [{ id: 'in', portKey: 'COMPLETED', semantic: 'SUCCESS', label: 'Completed' }],
    outputPorts: [],
    supportedScopes: ['INSTANCE'],
    supportsSla: false,
    supportsForm: false,
    supportsAssignee: false,
    handlerKey: 'end',
  },
  APPROVAL: {
    typeKey: 'APPROVAL',
    kind: 'HUMAN_TASK',
    displayName: 'Approval',
    icon: 'CheckCircle',
    color: '#3B82F6',
    configSchema: {
      type: 'object',
      properties: {
        name: { type: 'string' },
        assigneeResolver: { type: 'object' },
        approvalMode: { type: 'string', enum: ['SINGLE', 'ALL', 'ANY', 'THRESHOLD'] },
        allowedActions: { type: 'array' },
        form: { type: 'object' },
        sla: { type: 'object' },
      },
      required: ['name', 'assigneeResolver'],
    },
    inputPorts: [{ id: 'in', portKey: 'INPUT', semantic: 'SUCCESS', label: 'Input' }],
    outputPorts: [
      { id: 'approved', portKey: 'APPROVED', semantic: 'BUSINESS_OUTCOME', label: 'Approved' },
      { id: 'rejected', portKey: 'REJECTED', semantic: 'BUSINESS_OUTCOME', label: 'Rejected' },
      { id: 'request-change', portKey: 'REQUEST_CHANGE', semantic: 'BUSINESS_OUTCOME', label: 'Request Change' },
    ],
    supportedScopes: ['INSTANCE', 'EACH_PARTICIPANT'],
    supportsSla: true,
    supportsForm: true,
    supportsAssignee: true,
    handlerKey: 'approval',
  },
  REVIEW: {
    typeKey: 'REVIEW',
    kind: 'HUMAN_TASK',
    displayName: 'Review',
    icon: 'Eye',
    color: '#8B5CF6',
    configSchema: {
      type: 'object',
      properties: {
        name: { type: 'string' },
        assigneeResolver: { type: 'object' },
        reviewActions: { type: 'array' },
        completionPolicy: { type: 'string', enum: ['ALL', 'ANY', 'THRESHOLD'] },
        form: { type: 'object' },
        sla: { type: 'object' },
      },
      required: ['name', 'assigneeResolver'],
    },
    inputPorts: [{ id: 'in', portKey: 'INPUT', semantic: 'SUCCESS', label: 'Input' }],
    outputPorts: [
      { id: 'completed', portKey: 'REVIEW_COMPLETED', semantic: 'BUSINESS_OUTCOME', label: 'Completed' },
      { id: 'returned', portKey: 'RETURNED', semantic: 'BUSINESS_OUTCOME', label: 'Returned' },
    ],
    supportedScopes: ['INSTANCE', 'EACH_PARTICIPANT'],
    supportsSla: true,
    supportsForm: true,
    supportsAssignee: true,
    handlerKey: 'review',
  },
  ASSIGNMENT: {
    typeKey: 'ASSIGNMENT',
    kind: 'HUMAN_TASK',
    displayName: 'Assignment',
    icon: 'User',
    color: '#F97316',
    configSchema: {
      type: 'object',
      properties: {
        name: { type: 'string' },
        assigneeResolver: { type: 'object' },
        assignmentMode: { type: 'string', enum: ['DIRECT_ONE', 'DIRECT_ALL', 'CLAIMABLE_POOL'] },
        completionPolicy: { type: 'string', enum: ['ALL', 'ANY', 'THRESHOLD'] },
        form: { type: 'object' },
        sla: { type: 'object' },
      },
      required: ['name', 'assigneeResolver'],
    },
    inputPorts: [{ id: 'in', portKey: 'INPUT', semantic: 'SUCCESS', label: 'Input' }],
    outputPorts: [
      { id: 'completed', portKey: 'COMPLETED', semantic: 'SUCCESS', label: 'Completed' },
      { id: 'timeout', portKey: 'TIMEOUT', semantic: 'TEMPORAL', label: 'Timeout' },
    ],
    supportedScopes: ['INSTANCE', 'EACH_PARTICIPANT'],
    supportsSla: true,
    supportsForm: true,
    supportsAssignee: true,
    handlerKey: 'assignment',
  },
  NOTIFICATION: {
    typeKey: 'NOTIFICATION',
    kind: 'AUTOMATION',
    displayName: 'Notification',
    icon: 'Mail',
    color: '#FBBF24',
    configSchema: {
      type: 'object',
      properties: {
        name: { type: 'string' },
        recipientResolver: { type: 'object' },
        channels: { type: 'array' },
        template: { type: 'object' },
        deliveryMode: { type: 'string' },
      },
      required: ['name', 'recipientResolver', 'channels'],
    },
    inputPorts: [{ id: 'in', portKey: 'INPUT', semantic: 'SUCCESS', label: 'Input' }],
    outputPorts: [{ id: 'sent', portKey: 'SENT', semantic: 'SUCCESS', label: 'Sent' }],
    supportedScopes: ['INSTANCE', 'EACH_PARTICIPANT'],
    supportsSla: false,
    supportsForm: false,
    supportsAssignee: false,
    handlerKey: 'notification',
  },
  CONDITION: {
    typeKey: 'CONDITION',
    kind: 'CONTROL',
    displayName: 'Condition (IF/ELSE)',
    icon: 'AlertTriangle',
    color: '#10B981',
    configSchema: {
      type: 'object',
      properties: {
        name: { type: 'string' },
        condition: { type: 'string' },
        mode: { type: 'string', enum: ['BOOLEAN', 'CASE', 'FIRST_MATCH'] },
        nullPolicy: { type: 'string', enum: ['NULL_AS_FALSE', 'ERROR', 'IS_NULL'] },
      },
      required: ['name', 'condition'],
    },
    inputPorts: [{ id: 'in', portKey: 'INPUT', semantic: 'SUCCESS', label: 'Input' }],
    outputPorts: [
      { id: 'true', portKey: 'TRUE', semantic: 'DECISION', label: 'True' },
      { id: 'false', portKey: 'FALSE', semantic: 'DECISION', label: 'False' },
      { id: 'default', portKey: 'DEFAULT', semantic: 'DECISION', label: 'Default' },
    ],
    supportedScopes: ['INSTANCE', 'EACH_PARTICIPANT'],
    supportsSla: false,
    supportsForm: false,
    supportsAssignee: false,
    handlerKey: 'condition',
  },
  SYSTEM: {
    typeKey: 'SYSTEM',
    kind: 'AUTOMATION',
    displayName: 'System Action',
    icon: 'Database',
    color: '#6B7280',
    configSchema: {
      type: 'object',
      properties: {
        name: { type: 'string' },
        connectorId: { type: 'string' },
        actionId: { type: 'string' },
        inputMapping: { type: 'object' },
        outputMapping: { type: 'object' },
        retryPolicy: { type: 'object' },
      },
      required: ['name'],
    },
    inputPorts: [{ id: 'in', portKey: 'INPUT', semantic: 'SUCCESS', label: 'Input' }],
    outputPorts: [
      { id: 'success', portKey: 'SUCCESS', semantic: 'SUCCESS', label: 'Success' },
      { id: 'error', portKey: 'ERROR', semantic: 'TECHNICAL', label: 'Error' },
    ],
    supportedScopes: ['INSTANCE', 'EACH_PARTICIPANT'],
    supportsSla: false,
    supportsForm: false,
    supportsAssignee: false,
    handlerKey: 'system-action',
  },
  DATA: {
    typeKey: 'DATA',
    kind: 'DATA_PURE',
    displayName: 'Data Table',
    icon: 'Collection',
    color: '#06B6D4',
    configSchema: {
      type: 'object',
      properties: {
        name: { type: 'string' },
        dataSource: { type: 'string' },
        filters: { type: 'array' },
      },
      required: ['name'],
    },
    inputPorts: [{ id: 'in', portKey: 'INPUT', semantic: 'SUCCESS', label: 'Input' }],
    outputPorts: [{ id: 'completed', portKey: 'COMPLETED', semantic: 'SUCCESS', label: 'Completed' }],
    supportedScopes: ['INSTANCE'],
    supportsSla: false,
    supportsForm: false,
    supportsAssignee: false,
    handlerKey: 'data-table',
  },
  HTTP: {
    typeKey: 'HTTP',
    kind: 'AUTOMATION',
    displayName: 'HTTP Request',
    icon: 'Link',
    color: '#EC4899',
    configSchema: {
      type: 'object',
      properties: {
        name: { type: 'string' },
        method: { type: 'string', enum: ['GET', 'POST', 'PUT', 'DELETE'] },
        url: { type: 'string' },
        headers: { type: 'object' },
        body: { type: 'string' },
        authType: { type: 'string' },
      },
      required: ['name', 'url'],
    },
    inputPorts: [{ id: 'in', portKey: 'INPUT', semantic: 'SUCCESS', label: 'Input' }],
    outputPorts: [
      { id: 'success', portKey: 'SUCCESS', semantic: 'SUCCESS', label: 'Success' },
      { id: 'error', portKey: 'ERROR', semantic: 'TECHNICAL', label: 'Error' },
    ],
    supportedScopes: ['INSTANCE'],
    supportsSla: false,
    supportsForm: false,
    supportsAssignee: false,
    handlerKey: 'http-request',
  },
  DATA_TRANSFORM: {
    typeKey: 'DATA_TRANSFORM',
    kind: 'DATA_PURE',
    displayName: 'Data Transform',
    icon: 'TrendingUp',
    color: '#84CC16',
    configSchema: {
      type: 'object',
      properties: {
        name: { type: 'string' },
        assignments: { type: 'array' },
        executionScope: { type: 'string', enum: ['INSTANCE', 'EACH_PARTICIPANT'] },
      },
      required: ['name', 'assignments'],
    },
    inputPorts: [{ id: 'in', portKey: 'INPUT', semantic: 'SUCCESS', label: 'Input' }],
    outputPorts: [{ id: 'completed', portKey: 'COMPLETED', semantic: 'SUCCESS', label: 'Completed' }],
    supportedScopes: ['INSTANCE', 'EACH_PARTICIPANT'],
    supportsSla: false,
    supportsForm: false,
    supportsAssignee: false,
    handlerKey: 'data-transform',
  },
  TIMER: {
    typeKey: 'TIMER',
    kind: 'WAIT',
    displayName: 'Timer / Delay',
    icon: 'Clock',
    color: '#EF4444',
    configSchema: {
      type: 'object',
      properties: {
        name: { type: 'string' },
        waitType: { type: 'string', enum: ['DURATION', 'UNTIL_DATETIME', 'BUSINESS_TIME'] },
        duration: { type: 'number' },
        durationUnit: { type: 'string' },
        untilDateTime: { type: 'string' },
        timezone: { type: 'string' },
      },
      required: ['name', 'waitType'],
    },
    inputPorts: [{ id: 'in', portKey: 'INPUT', semantic: 'SUCCESS', label: 'Input' }],
    outputPorts: [
      { id: 'fired', portKey: 'TIMER_FIRED', semantic: 'TEMPORAL', label: 'Timer Fired' },
      { id: 'error', portKey: 'ERROR', semantic: 'TECHNICAL', label: 'Error' },
    ],
    supportedScopes: ['INSTANCE', 'EACH_PARTICIPANT'],
    supportsSla: false,
    supportsForm: false,
    supportsAssignee: false,
    handlerKey: 'timer',
  },
  WAIT_EVENT: {
    typeKey: 'WAIT_EVENT',
    kind: 'WAIT',
    displayName: 'Wait for Event',
    icon: 'Zap',
    color: '#8B5CF6',
    configSchema: {
      type: 'object',
      properties: {
        name: { type: 'string' },
        eventType: { type: 'string' },
        correlationKeyPath: { type: 'string' },
        timeout: { type: 'number' },
      },
      required: ['name', 'eventType'],
    },
    inputPorts: [{ id: 'in', portKey: 'INPUT', semantic: 'SUCCESS', label: 'Input' }],
    outputPorts: [
      { id: 'received', portKey: 'EVENT_RECEIVED', semantic: 'TEMPORAL', label: 'Event Received' },
      { id: 'timeout', portKey: 'TIMEOUT', semantic: 'TEMPORAL', label: 'Timeout' },
    ],
    supportedScopes: ['INSTANCE', 'EACH_PARTICIPANT'],
    supportsSla: false,
    supportsForm: false,
    supportsAssignee: false,
    handlerKey: 'wait-event',
  },
  PARALLEL_SPLIT: {
    typeKey: 'PARALLEL_SPLIT',
    kind: 'CONTROL',
    displayName: 'Parallel Split',
    icon: 'ArrowLeftRight',
    color: '#F97316',
    configSchema: {
      type: 'object',
      properties: {
        name: { type: 'string' },
        branchMode: { type: 'string', enum: ['ALL', 'CONDITIONAL'] },
        branchCount: { type: 'number' },
      },
      required: ['name'],
    },
    inputPorts: [{ id: 'in', portKey: 'INPUT', semantic: 'SUCCESS', label: 'Input' }],
    outputPorts: [
      { id: 'branch1', portKey: 'BRANCH_1', semantic: 'DECISION', label: 'Branch 1' },
      { id: 'branch2', portKey: 'BRANCH_2', semantic: 'DECISION', label: 'Branch 2' },
      { id: 'branch3', portKey: 'BRANCH_3', semantic: 'DECISION', label: 'Branch 3' },
    ],
    supportedScopes: ['INSTANCE', 'EACH_PARTICIPANT'],
    supportsSla: false,
    supportsForm: false,
    supportsAssignee: false,
    handlerKey: 'parallel-split',
  },
  JOIN: {
    typeKey: 'JOIN',
    kind: 'CONTROL',
    displayName: 'Join',
    icon: 'ArrowRightLeft',
    color: '#10B981',
    configSchema: {
      type: 'object',
      properties: {
        name: { type: 'string' },
        joinPolicy: { type: 'string', enum: ['ALL', 'ANY', 'THRESHOLD'] },
        expectedBranches: { type: 'number' },
        cancelRemaining: { type: 'boolean' },
      },
      required: ['name'],
    },
    inputPorts: [
      { id: 'in1', portKey: 'BRANCH_1', semantic: 'DECISION', label: 'Branch 1' },
      { id: 'in2', portKey: 'BRANCH_2', semantic: 'DECISION', label: 'Branch 2' },
    ],
    outputPorts: [{ id: 'joined', portKey: 'JOINED', semantic: 'SUCCESS', label: 'Joined' }],
    supportedScopes: ['INSTANCE'],
    supportsSla: false,
    supportsForm: false,
    supportsAssignee: false,
    handlerKey: 'join',
  },
  SUBWORKFLOW: {
    typeKey: 'SUBWORKFLOW',
    kind: 'COMPOSITION',
    displayName: 'Subworkflow',
    icon: 'Layers',
    color: '#EC4899',
    configSchema: {
      type: 'object',
      properties: {
        name: { type: 'string' },
        workflowRef: { type: 'string' },
        inputMapping: { type: 'object' },
        outputMapping: { type: 'object' },
        waitPolicy: { type: 'string', enum: ['WAIT_FOR_COMPLETION', 'FIRE_AND_FORGET'] },
      },
      required: ['name', 'workflowRef'],
    },
    inputPorts: [{ id: 'in', portKey: 'INPUT', semantic: 'SUCCESS', label: 'Input' }],
    outputPorts: [{ id: 'completed', portKey: 'COMPLETED', semantic: 'SUCCESS', label: 'Completed' }],
    supportedScopes: ['INSTANCE'],
    supportsSla: false,
    supportsForm: false,
    supportsAssignee: false,
    handlerKey: 'subworkflow',
  },
};

export function getNodeDescriptor(nodeType: string): NodeTypeDescriptor | undefined {
  return NODE_TYPE_REGISTRY[nodeType];
}

export function getAllNodeDescriptors(): NodeTypeDescriptor[] {
  return Object.values(NODE_TYPE_REGISTRY);
}

export function getNodeDescriptorByKind(kind: NodeKind): NodeTypeDescriptor[] {
  return Object.values(NODE_TYPE_REGISTRY).filter(d => d.kind === kind);
}

export function getHandlerKey(nodeType: string): string {
  return NODE_TYPE_REGISTRY[nodeType]?.handlerKey || 'unknown';
}
