package com.acme.workflow.directory;

import com.acme.workflow.auth.CurrentUserService;
import com.acme.workflow.auth.PermissionService;
import com.acme.workflow.common.*;
import com.acme.workflow.identity.domain.*;
import com.acme.workflow.identity.repository.*;
import org.springframework.security.crypto.password.PasswordEncoder;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

import java.util.*;

@Service
public class DirectoryService {
    private final HrmUserRepository users;private final OrganizationUnitRepository organizations;private final SystemRoleRepository roles;
    private final PermissionRepository permissionRepository;private final UserRoleAssignmentRepository assignments;private final RolePermissionRepository rolePermissions;
    private final PasswordEncoder encoder;private final CurrentUserService current;private final PermissionService permissionService;private final AuditService audit;private final Jsons jsons;
    public DirectoryService(HrmUserRepository users,OrganizationUnitRepository organizations,SystemRoleRepository roles,PermissionRepository permissionRepository,
                            UserRoleAssignmentRepository assignments,RolePermissionRepository rolePermissions,PasswordEncoder encoder,CurrentUserService current,
                            PermissionService permissionService,AuditService audit,Jsons jsons){this.users=users;this.organizations=organizations;this.roles=roles;this.permissionRepository=permissionRepository;this.assignments=assignments;this.rolePermissions=rolePermissions;this.encoder=encoder;this.current=current;this.permissionService=permissionService;this.audit=audit;this.jsons=jsons;}

    public List<Map<String,Object>> users(String search,String status,String orgUnitId,boolean includeSubtree){
        Collection<String>orgIds=null;if(orgUnitId!=null&&!orgUnitId.isBlank()){OrganizationUnit org=organizations.findById(orgUnitId).orElseThrow(()->ApiException.notFound("Không tìm thấy đơn vị "+orgUnitId));orgIds=includeSubtree?organizations.findByHierarchyPathStartingWithOrderByHierarchyPathAsc(org.hierarchyPath).stream().map(o->o.id).toList():List.of(orgUnitId);}
        final Collection<String>selected=orgIds;String q=search==null?"":search.toLowerCase(Locale.ROOT);String normalized=status==null||status.isBlank()?null:normalizeStatus(status);
        return users.findAll().stream().filter(u->normalized==null||normalized.equals(u.status)).filter(u->selected==null||selected.contains(u.organizationUnitId))
                .filter(u->q.isBlank()||u.displayName.toLowerCase(Locale.ROOT).contains(q)||u.email.toLowerCase(Locale.ROOT).contains(q)||u.employeeCode.toLowerCase(Locale.ROOT).contains(q))
                .sorted(Comparator.comparing((HrmUser u)->organizations.findById(u.organizationUnitId).map(o->o.hierarchyPath).orElse("")).thenComparing(u->u.displayName)).map(this::userMap).toList();
    }
    public Map<String,Object> user(String id){return userMap(users.findById(id).orElseThrow(()->ApiException.notFound("Không tìm thấy người dùng "+id)));}
    private Map<String,Object>userMap(HrmUser user){
        OrganizationUnit org=organizations.findById(user.organizationUnitId).orElse(null);HrmUser manager=user.managerId==null?null:users.findById(user.managerId).orElse(null);Map<String,Object>m=new LinkedHashMap<>();
        m.put("id",user.id);m.put("externalId",user.employeeCode);m.put("employeeCode",user.employeeCode);m.put("username",user.username);m.put("displayName",user.displayName);m.put("email",user.email);m.put("phone",user.phone);m.put("jobTitle",user.jobTitle);m.put("role",user.jobTitle);m.put("organizationUnitId",user.organizationUnitId);m.put("organizationName",org==null?null:org.name);m.put("department",org==null?null:org.name);m.put("organizationCode",org==null?null:org.code);m.put("managerId",user.managerId);m.put("managerName",manager==null?null:manager.displayName);m.put("employmentLevel",user.employmentLevel);m.put("level",user.employmentLevel);m.put("status","ACTIVE".equals(user.status)?"Active":"Inactive");m.put("createdAt",user.createdAt);m.put("updatedAt",user.updatedAt);m.put("systemRoles",roleAssignments(user.id));return m;
    }
    private List<Map<String,Object>>roleAssignments(String userId){return assignments.findByUserId(userId).stream().map(a->{SystemRole role=roles.findById(a.roleId).orElse(null);if(role==null)return null;Map<String,Object>m=new LinkedHashMap<>();m.put("id",role.id);m.put("code",role.code);m.put("name",role.name);m.put("organizationScopeId",a.organizationScopeId);m.put("organizationScopeName",a.organizationScopeId==null?null:organizations.findById(a.organizationScopeId).map(o->o.name).orElse(null));return m;}).filter(Objects::nonNull).toList();}

    @Transactional public Map<String,Object>createUser(Map<String,Object>body){String orgId=required(body,"organizationUnitId");String actor=current.id();permissionService.require(actor,"USER_MANAGE",orgId);organizations.findById(orgId).orElseThrow(()->ApiException.notFound("Không tìm thấy đơn vị"));HrmUser u=new HrmUser();u.id=string(body,"id",Ids.uuid());u.employeeCode=requiredAny(body,"employeeCode","externalId");u.username=string(body,"username",u.employeeCode.toLowerCase(Locale.ROOT));String password=string(body,"password","Welcome@123");u.passwordHash=encoder.encode(password.isBlank()?"Welcome@123":password);u.displayName=required(body,"displayName");u.email=required(body,"email");u.phone=nullable(body.get("phone"));u.jobTitle=nullable(first(body,"jobTitle","role"));u.organizationUnitId=orgId;u.managerId=nullable(body.get("managerId"));u.employmentLevel=nullable(first(body,"employmentLevel","level"));u.status=normalizeStatus(string(body,"status","ACTIVE"));users.saveAndFlush(u);Map<String,Object>created=user(u.id);audit.append(actor,"CREATE","USER",u.id,orgId,null,created,null);return created;}
    @Transactional public Map<String,Object>updateUser(String id,Map<String,Object>body){HrmUser u=users.findById(id).orElseThrow(()->ApiException.notFound("Không tìm thấy người dùng"));Map<String,Object>before=user(id);String orgId=string(body,"organizationUnitId",u.organizationUnitId);String actor=current.id();permissionService.require(actor,"USER_MANAGE",orgId);u.displayName=string(body,"displayName",u.displayName);u.email=string(body,"email",u.email);if(body.containsKey("phone"))u.phone=nullable(body.get("phone"));if(body.containsKey("jobTitle")||body.containsKey("role"))u.jobTitle=nullable(first(body,"jobTitle","role"));u.organizationUnitId=orgId;if(body.containsKey("managerId"))u.managerId=nullable(body.get("managerId"));if(body.containsKey("employmentLevel")||body.containsKey("level"))u.employmentLevel=nullable(first(body,"employmentLevel","level"));u.status=normalizeStatus(string(body,"status",u.status));if(body.get("password")!=null&&!String.valueOf(body.get("password")).isBlank())u.passwordHash=encoder.encode(String.valueOf(body.get("password")));users.saveAndFlush(u);Map<String,Object>after=user(id);audit.append(actor,"UPDATE","USER",id,orgId,before,after,null);return after;}

    public List<Map<String,Object>>organizations(){return organizations.findAllByOrderByHierarchyPathAsc().stream().map(this::organizationMap).toList();}
    private Map<String,Object>organizationMap(OrganizationUnit o){Map<String,Object>m=new LinkedHashMap<>();m.put("id",o.id);m.put("code",o.code);m.put("name",o.name);m.put("unitType",o.unitType);m.put("hierarchyLevel",o.hierarchyLevel);m.put("parentId",o.parentId);m.put("hierarchyPath",o.hierarchyPath);m.put("headUserId",o.headUserId);m.put("headUserName",o.headUserId==null?null:users.findById(o.headUserId).map(u->u.displayName).orElse(null));m.put("status",o.status);m.put("directUserCount",users.countByOrganizationUnitId(o.id));return m;}
    @SuppressWarnings("unchecked") public List<Map<String,Object>>organizationTree(){List<Map<String,Object>>all=new ArrayList<>(organizations());Map<String,Map<String,Object>>byId=new LinkedHashMap<>();all.forEach(m->{m.put("children",new ArrayList<>());byId.put((String)m.get("id"),m);});List<Map<String,Object>>roots=new ArrayList<>();all.forEach(m->{String parent=(String)m.get("parentId");if(parent==null||!byId.containsKey(parent))roots.add(m);else((List<Map<String,Object>>)byId.get(parent).get("children")).add(m);});return roots;}
    @Transactional public Map<String,Object>createOrganization(Map<String,Object>body){String parentId=nullable(body.get("parentId"));String actor=current.id();permissionService.require(actor,"ORG_MANAGE",parentId==null?"ORG-COMPANY":parentId);OrganizationUnit parent=parentId==null?null:organizations.findById(parentId).orElseThrow(()->ApiException.notFound("Không tìm thấy đơn vị cha"));OrganizationUnit o=new OrganizationUnit();o.id=string(body,"id",Ids.uuid());o.code=required(body,"code");o.name=required(body,"name");o.unitType=string(body,"unitType","DEPARTMENT");o.parentId=parentId;o.hierarchyLevel=parent==null?0:parent.hierarchyLevel+1;o.hierarchyPath=(parent==null?"/":parent.hierarchyPath)+o.id+"/";o.headUserId=nullable(body.get("headUserId"));o.status="ACTIVE";organizations.saveAndFlush(o);Map<String,Object>created=organizationMap(o);audit.append(actor,"CREATE","ORGANIZATION",o.id,parentId,null,created,null);return created;}

    public List<Map<String,Object>>roles(){return roles.findAllByOrderByNameAsc().stream().map(this::roleMap).toList();}
    private Map<String,Object>roleMap(SystemRole role){Map<String,Object>m=new LinkedHashMap<>();m.put("id",role.id);m.put("code",role.code);m.put("name",role.name);m.put("description",role.description);m.put("builtIn",role.builtIn);m.put("status",role.status);m.put("createdAt",role.createdAt);m.put("permissions",rolePermissions.findByRoleId(role.id).stream().map(rp->permissionRepository.findById(rp.permissionCode).map(p->Map.of("code",p.code,"name",p.name)).orElse(Map.of("code",rp.permissionCode,"name",rp.permissionCode))).toList());return m;}
    @Transactional public Map<String,Object>createRole(Map<String,Object>body){String actor=current.id();permissionService.require(actor,"ROLE_MANAGE",null);SystemRole r=new SystemRole();r.id=string(body,"id",Ids.uuid());r.code=required(body,"code");r.name=required(body,"name");r.description=nullable(body.get("description"));r.builtIn=false;r.status="ACTIVE";roles.saveAndFlush(r);for(String code:list(body.get("permissions"))){if(!permissionRepository.existsById(code))throw ApiException.badRequest("INVALID_PERMISSION","Permission không tồn tại: "+code);rolePermissions.save(new RolePermission(r.id,code));}Map<String,Object>created=roleMap(r);audit.append(actor,"CREATE","SYSTEM_ROLE",r.id,null,null,created,null);return created;}
    @Transactional public List<Map<String,Object>>assignRoles(String userId,List<Map<String,Object>>body){HrmUser user=users.findById(userId).orElseThrow(()->ApiException.notFound("Không tìm thấy người dùng"));String actor=current.id();permissionService.require(actor,"ROLE_MANAGE",user.organizationUnitId);Object before=roleAssignments(userId);assignments.deleteByUserId(userId);assignments.flush();for(Map<String,Object>a:body){String roleId=required(a,"roleId");if(!roles.existsById(roleId))throw ApiException.badRequest("INVALID_ROLE","Role không tồn tại: "+roleId);UserRoleAssignment e=new UserRoleAssignment();e.id=Ids.uuid();e.userId=userId;e.roleId=roleId;e.organizationScopeId=nullable(a.get("organizationScopeId"));assignments.save(e);}List<Map<String,Object>>after=roleAssignments(userId);audit.append(actor,"ASSIGN_ROLES","USER",userId,user.organizationUnitId,before,after,null);return after;}

    private List<String>list(Object value){if(value==null)return List.of();return jsons.mapper().convertValue(value,jsons.mapper().getTypeFactory().constructCollectionType(List.class,String.class));}
    private String required(Map<String,Object>b,String k){Object v=b.get(k);if(v==null||String.valueOf(v).isBlank())throw ApiException.badRequest("REQUIRED_FIELD","Thiếu trường "+k);return String.valueOf(v);}private String requiredAny(Map<String,Object>b,String a,String c){Object v=first(b,a,c);if(v==null||String.valueOf(v).isBlank())throw ApiException.badRequest("REQUIRED_FIELD","Thiếu trường "+a);return String.valueOf(v);}private Object first(Map<String,Object>b,String a,String c){return b.containsKey(a)?b.get(a):b.get(c);}private String string(Map<String,Object>b,String k,String fallback){Object v=b.get(k);return v==null?fallback:String.valueOf(v);}private String nullable(Object v){return v==null||String.valueOf(v).isBlank()?null:String.valueOf(v);}private String normalizeStatus(String s){return"Active".equalsIgnoreCase(s)?"ACTIVE":"Inactive".equalsIgnoreCase(s)?"INACTIVE":s.toUpperCase(Locale.ROOT);}
}
